/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

/**
 *
 * @author latitude3
 */
public class TelaOrca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaOrca.class.getName());

    /**
     * Creates new form TelaOrca
     */
    public TelaOrca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCtg = new javax.swing.JTextField();
        txtCin = new javax.swing.JTextField();
        txtCout = new javax.swing.JTextField();
        txtPcm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPmp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPcp = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrc = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCtg.addActionListener(this::txtCtgActionPerformed);

        txtCin.setText(" ");

        jLabel1.setText("Check in:");

        jLabel2.setText("Check out:");

        jLabel3.setText("Categoria: ");

        jLabel4.setText("Café da manhã:");

        jLabel5.setText("Meia Pensão:");

        jLabel6.setText("Pensão Completa:");

        btnGerar.setText("Gerar Texto");
        btnGerar.addActionListener(this::btnGerarActionPerformed);

        txtOrc.setColumns(20);
        txtOrc.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        txtOrc.setRows(5);
        txtOrc.setText("Texto");
        jScrollPane1.setViewportView(txtOrc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCtg, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPmp)
                            .addComponent(txtPcp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCout)
                            .addComponent(txtPcm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGerar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnGerar)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String gerarBloco(String Cin, String Cout, double valor, String regime) {
    return "Período: " + Cin + " - " + Cout + "\n"
         + "Regime de alimentação: " + regime + "\n"
         + "Valor total: R$ " + valor + " + 10% de serviço/ Por apartamento\n\n";
    }
    
    private void txtCtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCtgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCtgActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
       String categoria = txtCtg.getText().toLowerCase();
       String Cin=txtCin.getText();
       String Cout=txtCout.getText();
       double cf = Double.parseDouble(txtPcm.getText().replace(",", "."));
       double mp = Double.parseDouble(txtPmp.getText().replace(",", "."));
       double pc = Double.parseDouble(txtPcp.getText().replace(",", "."));

    if (categoria.contains("mosteiro") && categoria.contains("casal")) {

    String texto = txtCtg.getText() + "\n\n"
            + "A arquitetura do Mosteiro, assim como das demais edificações do resort, remete a vilas interioranas, "
            + "com influências coloniais e um toque de inspiração italiana, criando uma atmosfera charmosa e tranquila para os hóspedes. "
            + "Essa unidade possui uma cama de casal, e é indicado para até duas pessoas.\n\n"
            
            + gerarBloco(Cin, Cout, cf, "Café da manhã")
            + gerarBloco(Cin, Cout, mp, "Meia Pensão")
            + gerarBloco(Cin, Cout, pc, "Pensão Completa");

    txtOrc.setText(texto);

    } else if(categoria.contains("mosteiro")&&categoria.contains("duplo")&& categoria.contains("solteiro")) {
            txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "A arquitetura do Mosteiro, assim como das demais edificações do resort, remete a vilas interioranas, "
                    + "com influências coloniais e um toque de inspiração italiana, criando uma atmosfera charmosa e tranquila para os hóspedes. "
                    + "Essa unidade possui duas camas de solteiros, e é indicado para até duas pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento"
                );
          } else if (categoria.contains("mosteiro")&&categoria.contains("triplo")){
              txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "A arquitetura do Mosteiro, assim como das demais edificações do resort, remete a vilas interioranas, "
                    + "com influências coloniais e um toque de inspiração italiana, criando uma atmosfera charmosa e tranquila para os hóspedes. "
                    + "Essa unidade possui duas camas de solteiros, e é indicado para até duas pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento"
                );
          } else if (categoria.contains("casario standard")&&categoria.contains("duplo")&&categoria.contains("casal")){
          txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal. Acomoda no máximo 2 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento"
                );
          }else if(categoria.contains("casario standard")&&categoria.contains("triplo")&&categoria.contains("casal")){
              txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e uma cama de solteiro. Acomoda no máximo 3 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento"
                );
          }else if(categoria.contains("casario standard")&&categoria.contains("triplo")&&categoria.contains("solteiro")){
                    txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui 3 camas de solteiros"+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento"
                );

          }else if (categoria.contains("casario standard")&&categoria.contains("quadrúplo")){
                     txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e duas camas de solteiros. Acomoda no máximo 4 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }else if(categoria.contains("casario luxo")&&categoria.contains("casal")){
                   txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Localizados nos casarios que remetem uma cidade de Paraty. A categoria Luxo e desfruta de um belo jardim com requinte e privacidade. Os quartos se distribuem entre o piso térreo e superior e estão em meio a uma natureza preservada."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          } else if (categoria.contains("casario luxo")&&categoria.contains("quadrúplo")){
                   txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui banheira, uma cama de casal e duas camas de solteiros. Acomoda no máximo 4 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }else if (categoria.contains("casario frente mar")&&categoria.contains("casal")&&categoria.contains("duplo")){
                txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e fica localizada de frente para o Mar. Acomoda no máximo 2 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }else if (categoria.contains("casario frente mar")&&categoria.contains("quadrúplo")){
                 txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e fica localizada de frente para o Mar. Acomoda no máximo 2 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }else if (categoria.contains("casario suíte")&&categoria.contains("duplo")){
                txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e fica localizada de frente para o Mar. Acomoda no máximo 2 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }else if(categoria.contains("chalé frente mar")&&categoria.contains("casal")){
                 txtOrc.setText(
            txtCtg.getText() + "\n\n" +
            "Essas suites são localizadas nos casarios que remetem uma cidade de Paraty. Cenário charmoso, temático e cercado de verde. Os apartamentos são distribuidos em piso térreo e superior. Essa unidade possui uma cama de casal e fica localizada de frente para o Mar. Acomoda no máximo 2 pessoas."+ "\n\n" 
                    + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Café da manhã." +"\n"
                    + "Valor total: R$ "+ cf+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Meia Pensão." +"\n"
                    + "Valor total: R$ "+ mp+" + 10% de serviço/ Por apartamento"+ "\n\n"
                + "Período:" + Cin+" "+"-"+" "+Cout+ "\n"
                    +"Regime de alimentação: Pensão Completa." +"\n"
                    + "Valor total: R$ "+ pc+" + 10% de serviço/ Por apartamento");
          }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaOrca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCin;
    private javax.swing.JTextField txtCout;
    private javax.swing.JTextField txtCtg;
    private javax.swing.JTextArea txtOrc;
    private javax.swing.JTextField txtPcm;
    private javax.swing.JTextField txtPcp;
    private javax.swing.JTextField txtPmp;
    // End of variables declaration//GEN-END:variables
}
